name: Ocuroot Work Continue

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to check out'
        required: true
        type: string

jobs:
  continue:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Download ocuroot binary
        run: |
          curl -L -o ocuroot https://downloads.ocuroot.com/ocuroot/0.3.5-2/linux-amd64/ocuroot
          chmod +x ocuroot

      - name: Configure Git
        run: |
          git config --global user.email "ocuroot-ci@example.com"
          git config --global user.name "Ocuroot CI"

      - name: Run ocuroot work continue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
        run: ./ocuroot work continue
