name: Ocuroot Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ocuroot binary
        run: |
          curl -L -o ocuroot https://downloads.ocuroot.com/ocuroot/0.3.5-7/linux-amd64/ocuroot
          chmod +x ocuroot

      - name: Configure Git
        run: |
          git config --global user.email "ocuroot-ci@example.com"
          git config --global user.name "Ocuroot CI"

      - name: Release all packages
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          ./ocuroot release new environments/release.ocu.star
          ./ocuroot release new nginx/release.ocu.star
          ./ocuroot release new kubernetes/release.ocu.star

      - name: Trigger following work
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: ./ocuroot work trigger
