name: Ocuroot Work Continue

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to check out"
        required: true
        type: string

run-name: Continue on ${{ github.event.inputs.commit_sha }}

jobs:
  continue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Download ocuroot binary
        run: |
          curl -L -o ocuroot ${{ vars.OCUROOT_BINARY }}
          chmod +x ocuroot

      - name: Configure Git
        run: |
          git config --global user.email "ocuroot-ci@example.com"
          git config --global user.name "Ocuroot CI"

      # Continue any work for this commit
      - name: Run ocuroot work continue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GH Actions token so we don't trigger workflows
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
        run: ./ocuroot work continue

      # Handle intent changes and trigger related work
      - name: Apply all intent
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GH Actions token so we don't trigger workflows
        run: |
          ./ocuroot state diff | xargs -r -n1 ./ocuroot state apply

      - name: Trigger following work
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} # Use the PAT token so we can trigger workflows
        run: ./ocuroot work trigger
        
