# This holds an example for a workflow that
# should be stored in the state branch
name: Ocuroot Apply Intent

on:
  push:
    branches: [state]
    paths:
      - "**/\\+*"
      - "**/\\+*/**"

jobs:
  intent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ocuroot binary
        run: |
          curl -L -o ocuroot ${{ vars.OCUROOT_BINARY }}
          chmod +x ocuroot

      - name: Configure Git
        run: |
          git config --global user.email "ocuroot-ci@example.com"
          git config --global user.name "Ocuroot CI"

      - name: Trigger work from intent
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: ./ocuroot work trigger --intent